version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./clickhouse/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9900:9000
    depends_on:
      - minio
      - createbuckets
  minio:
    image: quay.io/minio/minio
    container_name: minio
    hostname: minio
    command: server --address ":10000" --console-address ":10001" /data
    ports:
      - ${MINIO_SERVER_PORT}:10000
      - ${MINIO_DASHBOARD_PORT}:10001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:10000/minio/health/live']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        /usr/bin/mc alias set myminio http://minio:10000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}";
        /usr/bin/mc admin info myminio;
        /usr/bin/mc mb myminio/"${S3_BUCKET_NAME}";
        /usr/bin/mc policy set public myminio/"${S3_BUCKET_NAME}";
        exit 0;d
    # yamllint enable rule:line-length
